default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      exclude: |
        (?x)^(
        animation.py |
        driver.py |
        )$

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
        - id: check-ast
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-merge-conflict
        - id: end-of-file-fixer
        - id: name-tests-test
        - id: check-yaml
        - id: forbid-new-submodules
        - id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://gitlab.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-debugger
    - flake8-docstrings
    - flake8-eradicate
    - flake8-mutable
