default_language_version:
    python: python3.8

repos:
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    - id: black

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.812
#     hooks:
#     -   id: mypy

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
        - id: check-json
        - id: pretty-format-json
        - id: check-yaml
        - id: forbid-new-submodules
        - id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
